# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v3 or later

name: Build and test

on:
- pull_request
- push

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Build and test
        run: |-
          set -e
          go build .
          ./go-wait-for-it --help
          ./go-wait-for-it \
              --timeout 2 \
              --service github.com:80 \
              --service github.com:443 \
              -- \
              sh -c 'exit 123' \
            || [ $? = 123 ]
          go test -v -coverprofile=cover.out ./...
          go tool cover -func=cover.out | tee cover-report.txt
          [[ $(grep ^total: < cover-report.txt | awk '{print $3}') = 100.0% ]]
      - name: "Require empty diff for: goimports"
        run: |-
          set -e
          ( cd /tmp && go get golang.org/x/tools/cmd/goimports )
          git ls-files \*.go | xargs goimports -w
          git ls-files \*.go | xargs git diff --exit-code --
      - name: "Require empty diff for: gofmt"
        run: |-
          set -e
          git ls-files \*.go | xargs gofmt -s -w
          git ls-files \*.go | xargs git diff --exit-code --
      - name: "Require empty diff for: go mod tidy"
        run: |-
          set -e
          go mod tidy -v
          git diff --exit-code -- go.mod go.sum
